[package]
name = "biome-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_js_parser = "0.5.7"
biome_js_syntax = "0.5.7"
biome_js_semantic = "0.5.7"
biome_rowan = "0.5.7" 