[package]
name = "oxc_span"
version = "0.1.0"
edition = "2021"

[dependencies]
oxc_semantic = "0.25.0"
oxc_allocator = "0.25.0"  
oxc_parser = "0.25.0"
oxc_ast = "0.25.0"
oxc_sourcemap = "0.25.0"
oxc_span = "0.25.0"